#!/bin/bash
##


###################################################################################################################################################
## Copyright (C) 2010 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################

## On récupère les emplacements des répertoires de travail de OSagence
eval "$(grep 'rept1=\"' '/usr/share/osagence/osa-menu')"
eval $(grep 'rept=\"' "${rept1}/rept/rept.cfg")


eval "$(cat ${rept1}/traduc.tmp)"
a021=$(echo "${a021}" | sed 's/<br>/µ/g')

if [ -z "${a124}" ]; then
	{
		lgaff="EN"
	}
else
	{
		lgaff="${a124}"
	}
fi

lang1="${a126}"
lang2="${a127}"

while true
do
	
	if [ -e "${rept1}/lg1.tmp" ]; then
		{
			eval $(cat "${rept1}/lg1.tmp")
		}
	fi
	
	if [ -e "${rept1}/lg2.tmp" ]; then
		{
			eval $(cat "${rept1}/lg2.tmp")
		}
	fi
	
	if [ -e "${rept1}/lg3.tmp" ]; then
		{
			eval $(cat "${rept1}/lg3.tmp")
		}
	fi
	langue2="$(grep -v '#' ${rept}/conf/.langues.txt | sed 's/>$/>@/g')"
	
	lg1="<button><label>${a124}_lg1</label></button>"
	
	if [ ! -z "${a124}" ]; then
		{
			lg2="<button><label>${a128}_lg2</label></button>"
		}
	else
		{
			lg2=""
		}
	fi
	
	if [ ! -z "${a128}" ]; then
		{
			lg3="<button><label>${a132}_lg3</label></button>"
		}
	else
		{
			lg3=""
		}
	fi
	
	if [ "${EXIT}" != "trad auto" ]; then
		{
			while true
			do
				export MAIN_DIALOG='<window title="Choix de la langue à visualiser ou modifier." decorated="true" window_position="1" icon-name="gtk-home" width_request="400">
										<vbox>
											<hbox>
												'${lg1}${lg2}${lg3}'
											</hbox>
										</vbox>
										<action signal="delete-event">exit:Annuler</action>
									</window>'
									eval $(gtkdialog --program=MAIN_DIALOG)
				
				if [ "${EXIT}" == "${a124}_lg1" ]; then
					{
						trad="Première traduction"
						lgaff="${a124}"
						lang1="${a126}"
						lang2="${a127}"
						break
					}
				fi
				
				if [ "${EXIT}" == "${a128}_lg2" ]; then
					{
						trad="Deuxième traduction"
						lgaff="${a128}"
						lang1="${a130}"
						lang2="${a131}"
						break
					}
				fi
				
				if [ "${EXIT}" == "${a132}_lg3" ]; then
					{
						trad="Troisième traduction"
						lgaff="${a132}"
						lang1="${a134}"
						lang2="${a135}"
						break
					}
				fi

			done
		}
	fi
	
	if [ -z "${lgaff}" ]; then
		{
			lgaff="EN"
		}
	fi
	
	old_IFS=$IFS
	IFS="@"
	langue00="$(echo ${langue2} | grep ${lgaff})"
	langue01="$(echo ${langue2} | grep -v ${lgaff})"
	langue1="${langue00}${langue01}"
	IFS=$old_IFS
	
	if [ -z "${lang1}" ]; then
		{
			lang1="_"
		}
	fi

	if [ -z "${lang2}" ]; then
		{
			lang2="_"
		}
	fi
	
	lang2=$(echo "${lang2}" | sed 's/<br>/µ/g')
	
	if [ -e "$HOME/bin/google_translate" ]; then
		{
			bttrad="<button><label>"trad auto"</label></button>"
		}
	else
		{
			bttrad=""
		}
	fi
								
	## Fenêtre GTKdialog permettant la saisie d'un traduction
							export MAIN_DIALOG='<window title="OSagence, '"${trad}"': '"${lgaff}"'" decorated="true" window_position="1" icon-name="gtk-home">
								<vbox>
								<hbox>
									<text>
										<label>"Langue: "</label>
									</text>
									<combobox>
										<variable>traduc</variable>
										'"${langue1}"'
									</combobox>
								</hbox>
									<text>
										<label>'${a020}'</label>
									</text>
									<entry max-length="64">
										<variable>lang1</variable>
										<default>'${lang1}'</default>
									</entry>
									
									<frame Description complète, 4000 caractères max.>
										<vbox>
											<text>
												<label>'${a021}'</label>
											</text>
											<edit wrap-mode="2">
												<variable>lang2</variable>
												<default>'${lang2}'</default>
											</edit>
										</vbox>
									</frame>
									<hbox>
										'${bttrad}'
										<button>
											<label>"Quitter"</label>
										</button>
										<button ok></button>
									</hbox>
								</vbox>
								<action signal="delete-event">exit:Annuler</action>
							</window>'
							eval $(gtkdialog --program=MAIN_DIALOG)
														
							lang2=$(echo "${lang2}" | sed 's/µ/<br>/g' | tr -d [:cntrl:])
							
	if [ -e "$HOME/bin/google_translate" ] && [ "${EXIT}" == "trad auto" ]; then
		{
				## Fenêtre GTKdialog permettant la saisie d'un traduction
							export MAIN_DIALOG='<window title="Traduction simplifiée" decorated="true" window_position="1" icon-name="gtk-home">
								<vbox>
									<frame "Description complète, 4000 caractères max.>
										<vbox>
											<text>
												<label>'${a021}'</label>
											</text>
											<edit wrap-mode="2">
												<variable>la021</variable>
											</edit>
										</vbox>
									</frame>
									<hbox>
										<button ok></button>
									</hbox>
								</vbox>
								<action signal="delete-event">exit:Annuler</action>
							</window>'
							eval $(gtkdialog --program=MAIN_DIALOG)
							
			if [ "${la021}" == "" ]; then
				 {
					 la021="${a021}"
				 }
			fi
			
			lgaff="$(echo $traduc | cut -d, -f1)"
			ta020="$(echo ${a020} | sed 's/\./ # /g')"
			ta021="$(echo ${la021} | sed 's/\./ # /g')"
			tlang1="$($HOME/bin/google_translate -f fr -t $(echo $lgaff | tr A-Z a-z) -w "${ta020}")"
			tlang2="$($HOME/bin/google_translate -f fr -t $(echo $lgaff | cut -d, -f1 | tr A-Z a-z) -w "${ta021}")"
			lang1="$(echo ${tlang1} | sed 's/ # /\./g' | sed 's/#//g')"
			lang2="$(echo ${tlang2} | sed 's/ # /\./g' | sed 's/#//g')"
		}
	fi
							
	if [ "${EXIT}" == "OK" ] && [ "${trad}" == "Première traduction" ]; then
		{
			a124="$(echo $traduc | cut -d, -f1)"
			a126="${lang1}"
			a127="${lang2}"
			lgaff="${a124}"
			echo -e "a124=\"${a124}\"\na126=\"${a126}\"\na127=\"${a127}\"\n" > "${rept1}/lg1.tmp"
		}
	fi

	if [ "${EXIT}" == "OK" ] && [ "${trad}" == "Deuxième traduction" ]; then
		{
			a128="$(echo $traduc | cut -d, -f1)"
			a130="${lang1}"
			a131="${lang2}"
			lgaff="${a128}"
			echo -e "a128=\"${a128}\"\na130=\"${a130}\"\na131=\"${a131}\"\n" > "${rept1}/lg2.tmp"
		}
	fi

	if [ "${EXIT}" == "OK" ] && [ "${trad}" == "Troisième traduction" ]; then
		{
			a132="$(echo $traduc | cut -d, -f1)"
			a134="${lang1}"
			a135="${lang2}"
			lgaff="${a132}"
			echo -e "a132=\"${a132}\"\na134=\"${a134}\"\na135=\"${a135}\"\n" > "${rept1}/lg3.tmp"			
		}
	fi
	
	if [ "${EXIT}" == "Quitter" ]; then
		{
			break
		}
	fi

done

exit 0
