#!/bin/bash
##


###################################################################################################################################################
## Copyright (C) 2010 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################


## On récupère les emplacements des répertoires de travail de OSagence
eval "$(grep 'rept1=\"' '/usr/share/osagence/osa-menu')"
eval $(grep 'rept=\"' "${rept1}/rept/rept.cfg")

## On vérifie l'existence des paramètres secrets (non fournis aux négociateurs)
if [ ! -e "${rept}/conf/osa-sec.cfg" ]; then
	{
		exit 0
	}
fi

while true
do
	## Type de recherche
	tsearch=$(zenity --width=400 --height=400 --list --column "" --radiolist\
							--title="Choisissez le type de votre recherche" \
							--text="Le motif de votre recherche ne sera appliqué qu'au champs indiqué" \
							--column="" \
							FALSE Nom_du_Mandataire_#a114 \
							FALSE N°_de_tél._du_Mandataire_#a120 \
							FALSE Ville_réelle_du_bien_#a119 \
							FALSE CP_réel_du_bien_#a118 \
							FALSE Date_de_prise_du_mandat_#a113 \
							FALSE Négociateur_#a123 \
							FALSE Prix_NV_#a011 \
							TRUE Rechercher_partout) || exit 0

	if [ "${tsearch}" != "Rechercher_partout" ]; then
		{
			tsearch1="$(echo ${tsearch}	| cut -d# -f1 | sed 's/_/ /g')"
			tsearch="#$(echo ${tsearch}	| cut -d# -f2)"
		}
	else
		{
			tsearch=""
			tsearch1="tous les champs"
		}
	fi
						
	if [ "${tsearch}" == "#a113" ]; then
		{
			search=$(zenity --calendar --date-format="%d/%m/%Y" --title="Date de prise du mandat." --text="Choisir la date à rechercher") || exit 0
		}
	else
		{
			## Saisie du motif de recherche
			search=$(zenity --entry --entry-text=${search} --title="Rechercher un bien" --text="Entrez votre recherche") || exit 0
		}
	fi

	brut=$(find "${rept}/catalogue/fiches/" -name *.php \! -name "Copy*" | xargs grep -irH "${search}")

	old_IFS=$IFS
	IFS=";"
	result=$(echo ${brut} | sed "s;${rept}/catalogue/fiches/;;g" | sed "s;/dat.*:\\$;#;g" | grep "${tsearch}")


	result1=$(echo "${result}" | cut -d'#' -f1)
	nbresul=$(echo "${result}" | wc -l)

	zenity --width=400 --height=800 --list --column "" \
							--title="Recherche ${tsearch1}" \
							--text="Votre recherche sur ${search} retourne ${nbresul} résultat" \
							--column="" \
							${result1} || break
	IFS=${old_IFS}
done
exit 0
