#!/bin/bash
##


###################################################################################################################################################
## Copyright (C) 2010 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################

## On récupère les emplacements des répertoires de travail de OSagence
eval "$(grep 'rept1=\"' '/usr/share/osagence/osa-menu')"
eval $(grep 'rept=\"' "${rept1}/rept/rept.cfg")

## On vérifie l'existence des paramètres secrets (non fournis aux négociateurs)
if [ ! -e "${rept}/conf/osa-sec.cfg" ]; then
	{
		exit 0
	}
fi

## Lecture de la configuration
eval $(grep -v "^#" "${rept}/conf/osa.cfg")
eval $(grep -v "^#" "${rept}/conf/osa-sec.cfg")
## On vérifie qu'il n'y ai pas d'autre instance de ce script en cours, et on propose de la stopper le cas échéant
if [ -s /tmp/osagence-lock ]; then
	{
		if [ "$(cat /tmp/osagence-lock)" == "lock" ]; then
			{
				timeout 30 zenity --warning --text="Un processus de synchronisation est déjà en cours.\nPatientez quelques minutes.\nSi après 30min le problème persiste redémarrez votre PC.\nAprès redémarrage, une nouvelle tentative de synchronisation sera effectée,\nvous devrez donc attendre à nouveau."
				exit 0
			}
		else
			{
				rm -f /tmp/osagence-lock
			}
		fi
	}
fi

## Écriture du fichier de verrouillage d'OSagence pendant le temps de synchronisation
echo "lock" > /tmp/osagence-lock
	
aa="0"
while [ "$aa" != "60" ] ## Boucle pour faire 60 tests max, soit 10min
do
	## Si non connecté, 10s d'attente et relance le test
	ping -c1 google.fr >/dev/null
	if [ $? != "0" ]; then
	{
		sleep 10
		((aa++))
	}
	else
	{
		break
	}
	fi	
done

if [ "$aa" != "60" ]; then
	{
		## On crée un fichier de test
		id="$(ls -a ${rept1}/ID | grep '.id' | head -1 | cut -d"." -f2)"
		date +%s > "${rept1}/pro-${id}.txt"
		## Synchronisation du PC lors du démarrage
		transfert="fail"
		## On inscrit l'heure de début pour mémoriser la durée de la synchronisation
		time="$(date +'%H:%M')"

## Synchronisation
lftp ftp://${ftpus}:${ftpmdp}@${ftpserv} << EOF
rm /protege/pro-${id}.txt
mirror -e -x blog / ${rept}/catalogue/
put -O /protege ${rept1}/pro-${id}.txt
get1 -o ${rept}/catalogue/protege/pro-${id}.txt /protege/pro-${id}.txt
quit 0
EOF
		
		if [ "$(cat ${rept}/catalogue/protege/pro-${id}.txt)" == "$(cat ${rept1}/pro-${id}.txt)" ]; then
			{
				transfert="OK"
				rm -f "${rept1}/pro-${id}.txt"
			}
		fi
	}
fi

if [ "${transfert}" == "OK" ]; then
	{
		## Inscription de la date et de l'heure de la dernière synchronisation
		echo "Dernière synchronisation de ce PC le\\n $(date)" > "${rept1}/date-sync.temps"
		
		## Calcul de la durée de la synchro
		time1="$(cat ${rept1}/date-sync.temps | cut -d"," -f2 | cut -d":" -f1,2 | sed 's/ //g')"
					
		timet=$(($(date -d "${time1}" +"%s")-$(date -d "${time}" +"%s")))
		if [ "${timet}" -lt "0" ]; then
			{
				timef=$(((${timet}+(24*3600))/60))
			}
		else
			{
				timef=$((${timet}/60))
			}
		fi
		
		echo "La dernière synchronisation a durée ${timef} min." > "${rept1}/temps-sync.temps"
	
		rm -f /tmp/osagence-lock
	}
else
	{
		echo "fail" > /tmp/osagence-lock
		timeout 120 zenity --warning --text="La synchronisation est actuellement impossible.\nContrôlez votre connexion à internet puis redémarrez votre PC"
	}
fi
if [ "${master}" == "$(ls -a ${rept1}/ID/ | grep '.id')" ]; then
	{
		rsync -r -t -p -o -g -v --progress -c -l --numeric-ids -z -b --backup-dir="${rept1}/Sauvegarde_OSa/fichiers_supprimes" --del "${rept}" "${rept1}/Sauvegarde_OSa/"
		cd "${rept1}/Sauvegarde_OSa/.osagence/conf"
		mv "${rept1}/Sauvegarde_OSa/.osagence/conf/osa.cfg" "${rept1}/Sauvegarde_OSa/.osagence/conf/osa-modif.cfg"
		awk 'i;/@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/{i=2}' "${rept1}/Sauvegarde_OSa/.osagence/conf/osa-modif.cfg" > "${rept1}/Sauvegarde_OSa/.osagence/conf/osa.cfg"
		tar -zcvf "config-standalone.tar.gz" "echelle.png" ".LOCK" ".tmp" "entete-dpe.png" ".negociateur.txt" ".types-annonce.txt" ".chauffage.txt" "GES-curseur.png" "no_image.png" ".types-de-biens.txt" "config-dpe.cfg" "GES-echelle.png" "osa.cfg" ".var.txt" "curseur.png" "icon.png" "stop.sh" "dpe-def.jpg" ".langues.txt" "th_dpe-def.jpg"
		rm -f "${rept1}/Sauvegarde_OSa/.osagence/conf/osa.cfg"
		mv "${rept1}/Sauvegarde_OSa/.osagence/conf/osa-modif.cfg" "${rept1}/Sauvegarde_OSa/.osagence/conf/osa.cfg"
lftp ftp://${ftpus}:${ftpmdp}@${ftpserv} << EOF
put -O /envoi ${rept1}/Sauvegarde_OSa/.osagence/conf/config-standalone.tar.gz
quit 0
EOF

		rm -f "${rept1}/Sauvegarde_OSa/.osagence/conf/config-standalone.tar.gz"
	}
fi

exit 0
		

