#!/bin/bash
##


###################################################################################################################################################
## Copyright (C) 2010 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################

## Reprise du focus sur la fenêtre en cours si OSa-menu déjà lancé
wmctrl -a menu-OSagence
if [ $? == "0" ]; then
	{
		exit 0
	}
fi

## Répertoires de travail
# /!\ pas de "/" à la fin du chemin
	## répertoire des fichiers temporaires propre à chaque poste
	rept1="$HOME/.osa-tmp"
	
	## Choix du répertoire de travail qui doit être partagé entre tous les postes si utilisation multi-postes
	if [ ! -e "${rept1}/rept/rept.cfg" ]; then
		{
			## si il n'existe pas, on crée le répertoire des fichiers temporaires propre à chaque poste
			if [ ! -d "${rept1}/rept" ]; then
				{
					mkdir -p "${rept1}/rept"
				}
			fi
			
			nvrept=$(zenity --entry --entry-text="$HOME/.osagence" --title="Répertoire de travail" --text="Entrez ici le chemin du répertoire de travail de OSagence\nSauf cas particuliers, laissez la valeur par défaut.")
			nvrept1=$( echo ${nvrept%/} | sed "s;$HOME;\$HOME;g")
			# Création du fichier de configuration contenant le chemin du répertoire de travail
			echo -e "# répertoire de travail à placer dans le répertoire partagé/synchronisé en cas d'utilisation multipostes ( par ex. avec Hubic )\n# /!\\ pas de / à la fin du chemin\nrept=\"${nvrept1}\"" > "${rept1}/rept/rept.cfg"
		}
	fi
	
	# Lecture du fichier de configuration contenant le chemin du répertoire de travail
	eval $(grep 'rept=\"' "${rept1}/rept/rept.cfg")

## Verification de la presence du paquet timeout 
if type &>/dev/null timeout; then prst="oui"; fi
if [ "${prst}" != "oui" ]; then
	{
		tmo=""
		zenity --question --ok-label="Installer" --text="Le paquet Timeout n'est pas installé\nVoulez-vous l'installer ?" && tmo="oui"
		
		if [ "${tmo}" == "oui" ]; then
			{
				grep $(ls -i /var/lib/dpkg/lock | awk '{print $1}') /proc/locks >> /dev/null
				if [[ $? == 0 ]]; then
					{
						while true
						do
							zenity --question --text="Un autre gestionnaire de paquets est en cours d'utilisation\nFermez le avant que cliquer sur OK." || break
							grep $(ls -i /var/lib/dpkg/lock | awk '{print $1}') /proc/locks >> /dev/null
							if [[ $? != 0 ]]; then
								{
									xterm -title 'label' -e "\
									echo -e \"\E[37;44m\033[1m $(echo "Entrez votre mot de passe administrateur") \033[0m\"
									eval $(echo 'sudo apt-get install timeout')"
									break
								}
							fi
						done
					}
				else
					{
						xterm -title 'label' -e "\
						echo -e \"\E[37;44m\033[1m $(echo "Entrez votre mot de passe administrateur") \033[0m\"
						eval $(echo 'sudo apt-get install timeout')"
					}
				fi
			}
		fi
	}
fi

## Vérification de l'existence des répertoires de configuration
if [ ! -e "${rept}/conf/osa.cfg" ]; then
	{
		if [ ! -d "${rept}/" ]; then
			{
				mkdir -p "${rept}/"
			}
		fi
		tar -zxvf "/usr/share/osagence/data.tar.gz" -C "${rept}/"
	}
fi

## Indiquez si ce PC est un PC avec OSagence en version complète ou en version standalone pour négociateurs
if [ -e "${rept}/conf/pre.osa-sec.cfg" ]; then
	{
		standa=""
		zenity --question --ok-label="Standalone" --cancel-label="Gestion directe" --text="Voulez-vous que ce PC soit défini comme PC Standalone pour négociateur?\n\nOu comme PC permettant la gestion directe du site.\n\nUn PC Standalone permet de créer des fiches puis de les transmettre vers l'agence pour attribution d un n° de mandat et validation.\n\nUn PC de gestion directe permet d envoyer directement les fiches vers l'agence.\n Attention un PC à gestion directe demande beaucoup plus de configurations." && standa="oui"
		if [ "${standa}" == "oui" ]; then
			{
				rm -f "${rept}/conf/pre.osa-sec.cfg"
				osa_url=""
				zenity --question --ok-label="Éditer" --cancel-label="Non" --text="En version Standalone, pour envoyer vos fiches à l agence vous devez indiquer les paramètres d accés au serveur de transfert.\nFaites le maintenant ou répondez Non pour ignorer cette étape et juste tester OSagence." && osa_url="oui"
				
				if [ "${standa}" == "oui" ]; then
					{
						## On vérifie l'existance du paquet Geany
						if [ -e /usr/bin/geany ]; then
							{
								gean="geany"
							}
						else
							{
								#On récupère l'application par défaut pour le texte brut
								gean="$(xdg-mime query default text/plain | sed 's/\.desktop//g')"
							}
						fi
						
						if [ "${gean}" == "" ]; then
							{
								gean="xdg-open"
							}
						fi
						
						mv "${rept}/conf/pre.osa-url.cfg" "${rept}/conf/osa-url.cfg"
						eval $(${gean} "${rept}/conf/osa-url.cfg")
					}
				fi
		
			}
		else
			{
				mv "${rept}/conf/pre.osa-sec.cfg" "${rept}/conf/osa-sec.cfg"
			}
		fi
	}
fi
		
## Vérification/création du répertoire ID
if [ ! -d "${rept1}/ID" ]; then
	{
		mkdir -p "${rept1}/ID"
	}
fi
	
## On crée un fichier d'identification unique pour cette installation de OSagenge (utile pour le multiposte)
if [ -z "$(ls -a ${rept1}/ID/.*.id)" ]; then
	{
		while true
		do
			id=$(zenity --entry --entry-text=${USER} --title="Choisissez un identifiant" --text="Entrez le nom qui identifiera votre poste dans OSagence.\nLes autres utilisateurs seront prévenus de la référence que vous modifiez.")
			[ ! -z "${id}" ] && break
		done
		id="$(echo ${id} | sed 's/-/_/g' | sed 's/ /_/g')-$(date +%s)"
		echo ";-)" > "${rept1}/ID/.${id}.id"
	}
fi


if [ -e "${rept}/conf/osa-url.cfg" ]; then
	{
		eval $(grep -v "^#" "${rept}/conf/osa-url.cfg")
	}
fi

if [ ! -e "${rept}/conf/osa-sec.cfg" ]; then
	{
		if [ ! -d "${rept}/conf" ]; then
			{
				mkdir -p "${rept}/conf"
			}
		fi
		
		if [ ! -d "${rept}/catalogue/fiches" ]; then
			{
				mkdir -p "${rept}/catalogue/fiches"
			}
		fi
		
		if [ ! -d "${rept}/catalogue/privees" ]; then
			{
				mkdir -p "${rept}/catalogue/privees"
			}
		fi
		
		if [ ! -d "${rept1}/fiches" ]; then
			{
				mkdir -p "${rept1}/fiches"
			}
		fi
		
		if [ ! -d "${rept1}/ID" ]; then
			{
				mkdir -p "${rept1}/ID"
			}
		fi
		
		if [ -z "$(ls -a ${rept1}/ID/ | grep '.id')" ]; then
			{
				echo ";-)" > "${rept1}/ID/.${USER}-$(date +%s).id"
			}
		fi
		
		if [ -e "${rept}/conf/osa-url.cfg" ]; then
			{
				curl -f "http://${idstand}:${passstand}@${urlstand}/envoi/config-standalone.tar.gz" > ${rept1}/config-standalone.tar.gz
				tar -zxvf "${rept1}/config-standalone.tar.gz" -C "${rept}/conf/"
				rm -f "${rept1}/config-standalone.tar.gz"
			}
		fi
		eval $(grep -v "^#" "${rept}/conf/osa.cfg")
	}
else
	{
		eval $(grep -v "^#" "${rept}/conf/osa.cfg")
		testmaj="no"
		ID="$(ls -a ${rept1}/ID/ | grep '.id')"
		
		if [ "${urlmaj}" != "" ]; then
			{
				curl -f "http://${idmaj}:${passmaj}@${urlmaj}/maj/${ID}" >> /dev/null && testmaj="OK"
			}
		fi
		
		if [ "${testmaj}" == "OK" ]; then
			{
				## Lecture de la configuration
				eval $(grep -v "^#" "${rept}/conf/osa-sec.cfg")
				zenity --warning --text="Une mise à jour OSagence va être effectuée.\nSi un mot de passe vous est demandé, c'est celui qui permet d'allumer votre ordinateur."
				chmod +x $HOME/Hubic/.scripts/maj-osa.sh; $HOME/Hubic/.scripts/maj-osa.sh
				lftp ftp://${ftpus}:${ftpmdp}@${ftpserv}  -e "rm /maj/${ID}; quit"
				
				exit 0
			}
		fi
	}
fi

## Proposition de définition du PC comme Maître si aucun Maître n'est encore défini et si ce PC n'est pas un PC négociateur standalone
if [ "${master}" == ".PC_maitre.id" ] && [ -e "${rept}/conf/osa-sec.cfg" ]; then
	{
		mast=""
		zenity --question --ok-label="PC Maître" --cancel-label="Non" --text="Voulez-vous que ce PC soit défini comme PC Maître ?\n\nSi vous n'utilisez OSagence que sur un seul PC définissez le en tant que Maître.\n\n Le PC Maître est le poste principal de vôtre agence, c est le seul qui pourra réaliser des diffusions programmées.\nLes autres ne pourront faire que des diffusions ponctuelles.\n\nC est également celui qui gérera les sauvegardes de votre catalogue." && mast="oui"
		if [ "${mast}" == "oui" ]; then
			{
				sed -i "s/\.PC_maitre\.id/$(ls -a ${rept1}/ID/ | grep '.id')/g" "${rept}/conf/osa.cfg"
			}
		fi
	}
fi

while true
do
	if [ -e "${rept1}/poliris/diff-prog.txt" ] && [ "${master}" == "$(ls -a ${rept1}/ID/ | grep '.id')" ]; then
		{
			advert="<hbox>
						<pixmap>
							<width>200</width>
							<input file>/usr/share/osa-diffusion/pixmaps/auto-diff.png</input>
						</pixmap>
					</hbox>"
					
			prog_diff="<hbox>
							<pixmap>
								<width>48</width>
								<input file>/usr/share/osa-diffusion/pixmaps/osa-dif-prog.png</input>
							</pixmap>
							<button>
								<label>\"__Program. Diffusion__\"</label>
							</button>
						</hbox>"
			prog_diff1=""
		}
	else
		{
			if [ "${master}" == "$(ls -a ${rept1}/ID/ | grep '.id')" ]; then
				{
					advert="<hbox>
								<pixmap>
									<width>200</width>
									<input file>/usr/share/osa-diffusion/pixmaps/pas-diff.png</input>
								</pixmap>
							</hbox>"
					prog_diff="<hbox>
									<pixmap>
										<width>48</width>
										<input file>/usr/share/osa-diffusion/pixmaps/osa-dif-prog.png</input>
									</pixmap>
									<button>
										<label>\"__Program. Diffusion__\"</label>
									</button>
								</hbox>"
				}
			else
				{
					advert=""
					prog_diff=""
				}
			fi
						
			prog_diff1="<hbox>
							<pixmap>
								<width>48</width>
								<input file>/usr/share/osa-diffusion/pixmaps/osa-diffusion.png</input>
							</pixmap>
							<button>
								<label>\"________Diffusion________\"</label>
							</button>
						</hbox>"
		}
	fi
	
	## On vérifie l'existence des paramètres secrets (non fournis aux négociateurs)
	if [ -e "${rept}/conf/osa-sec.cfg" ]; then
		{
			export MAIN_DIALOG='<window title="menu-OSagence" window_position="1" decorated="true">
											<vbox>
												'${advert}'
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osagence/pixmaps/OSagence.png</input>
													</pixmap>
													<button>
														<label>"_______OSagence________"</label>
													</button>
												</hbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osa-affiches/pixmaps/affiches.png</input>
													</pixmap>
													<button>
														<label>"___Création affiches____"</label>
													</button>
												</hbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osa-dpe/pixmaps/osa-dpe.png</input>
													</pixmap>
													<button>
														<label>"_Étiquettes DPE et GES"</label>
													</button>
												</hbox>
												'${prog_diff}'
												'${prog_diff1}'
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osa-diffusion/pixmaps/osa-dif-black-white.png</input>
													</pixmap>
													<button>
														<label>"__Config. de diffusion__"</label>		
													</button>
												</hbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osagence/pixmaps/osa-manager.png</input>
													</pixmap>
													<button>
														<label>"______OSa-manager_____"</label>
													</button>
												</hbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osagence/pixmaps/osa-cherche.png</input>
													</pixmap>
													<button>
														<label>"____Recherche biens____"</label>
													</button>
												</hbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osagence/pixmaps/transfer.gif</input>
													</pixmap>
													<button>
														<label>"Synchronisation du PC"</label>		
													</button>
												</hbox>
												<hbox>
													<button>
														<label>"Quitter"</label>
													</button>
												</hbox>
											</vbox>
												
										</window>'
										
									eval $(gtkdialog --program=MAIN_DIALOG)
		}
	else
		{
			export MAIN_DIALOG='<window title="menu-OSagence" window_position="1" decorated="true">
											<vbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osagence/pixmaps/osa-nego.png</input>
													</pixmap>
													<text>
														<label>"OSagence Négociateurs"</label>
													</text>
												</hbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osagence/pixmaps/OSagence.png</input>
													</pixmap>
													<button>
														<label>"_______OSagence________"</label>
													</button>
												</hbox>
												<hbox>
													<pixmap>
														<width>48</width>
														<input file>/usr/share/osa-dpe/pixmaps/osa-dpe.png</input>
													</pixmap>
													<button>
														<label>"_Étiquettes DPE et GES"</label>
													</button>
												</hbox>
												<hbox>
													<button>
														<label>"Quitter"</label>
													</button>
												</hbox>
											</vbox>
												
										</window>'
										
									eval $(gtkdialog --program=MAIN_DIALOG)
		}
	fi
							
	if [ "${EXIT}" == "_______OSagence________" ]; then
		{
			/usr/share/osagence/osagence
		}
	elif [ "${EXIT}" == "___Création affiches____" ]; then
		{
			/usr/share/osa-affiches/osa-affiches
		}
	elif [ "${EXIT}" == "_Étiquettes DPE et GES" ]; then
		{
			/usr/share/osa-dpe/osa-gui-dpe
		}
	elif [ "${EXIT}" == "________Diffusion________" ]; then
		{
			/usr/share/osa-diffusion/osa-diffusion
		}
	elif [ "${EXIT}" == "__Program. Diffusion__" ]; then
		{
			/usr/share/osa-diffusion/osa-dif-prog
		}
	elif [ "${EXIT}" == "__Config. de diffusion__" ]; then
		{
			/usr/share/osa-diffusion/osa-dif-black-white
		}
	elif [ "${EXIT}" == "______OSa-manager_____" ]; then
		{
			/usr/share/osagence/osa-manager
		}
	elif [ "${EXIT}" == "____Recherche biens____" ]; then
		{
			/usr/share/osagence/osa-cherche
		}
	elif [ "${EXIT}" == "Synchronisation du PC" ]; then
		{
			if [ -s "${rept1}/temps-sync.temps" ]; then
				{
					messa="$(cat ${rept1}/temps-sync.temps)"
				}
			else
				{
					messa=""
				}
			fi
			
			sync=""
			zenity --question --ok-label="Synchroniser" --text="Voulez-vous synchroniser ce PC avec le site Web ?\nAttention cette opération peut prendre plusieurs\ndizaines de minutes et ne doit pas être interrompue.\n${messa}" && sync="oui"
			
			if [ "${sync}" == "oui" ]; then
				{
					
					## Transfert de la fiche vers le site web (depuis un terminal pour voir la progression)
					export MAIN_VIEWER_MOD_WAIT='<window title="viewer_wait_synchro" window_position="1" decorated="false">
												<vbox>
													<pixmap>
													<input file>/usr/share/osagence/pixmaps/transfer.gif</input>
													</pixmap>
													<text>
														<label>"La synchro. est en cours, veuillez ne pas interrompre."</label>
													</text>
												</vbox>
											</window>'
					##Lancer logo
					gtkdialog --program=MAIN_VIEWER_MOD_WAIT&
					
					## lancer script de synchro
					/usr/share/osagence/osa-sync
					
					sync=""
					
					
					## On reset l'image de pogression
					wmctrl -c viewer_wait_synchro
					
					zenity --info --text="$(cat ${rept1}/temps-sync.temps)"
				}
			fi
		}
	else
		{
			exit 0
		}
	fi
done
exit 0
