#!/bin/bash
##


###################################################################################################################################################
## Copyright (C) 2011 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################

## Reprise du focus sur la fenêtre en cours si OSagence déjà lancé
wmctrl -a "Créateur étiquettes energétiques"
if [ $? == "0" ]; then
	{
		exit 0
	}
fi

## On récupère les emplacements des répertoires de travail de OSagence
if [ -e "/usr/share/osagence/osa-menu" ]; then
	{
		eval "$(grep 'rept1=\"' '/usr/share/osagence/osa-menu')"
	}
else
	{
		rept1="$HOME/.osa-tmp"
		if [ ! -d "${rept1}/rept" ]; then
			{
				mkdir -p "${rept1}"
			}
		fi
	}
fi

## Choix du répertoire de travail qui doit être partagé entre tous les postes si utilisation multi-postes
if [ ! -e "${rept1}/rept/rept.cfg" ]; then
	{
		## si il n'existe pas, on crée le répertoire des fichiers temporaires propre à chaque poste
		if [ ! -d "${rept1}/rept" ]; then
			{
				mkdir -p "${rept1}/rept"
			}
		fi
		
		nvrept=$(zenity --entry --entry-text="$HOME/.osagence" --title="Répertoire de travail" --text="Entrez ici le chemin du répertoire de travail de OSagence\nSauf cas particuliers, laissez la valeur par défaut.")
		nvrept1=$( echo ${nvrept%/} | sed "s;$HOME;\$HOME;g")
		# Création du fichier de configuration contenant le chemin du répertoire de travail
		echo -e "# répertoire de travail à placer dans le répertoire partagé/synchronisé en cas d'utilisation multipostes ( par ex. avec Hubic )\n# /!\\ pas de / à la fin du chemin\nrept=\"${nvrept1}\"" > "${rept1}/rept/rept.cfg"
		mkdir -p "${nvrept}"
	}
fi

# Lecture du fichier de configuration contenant le chemin du répertoire de travail
eval $(grep 'rept=\"' "${rept1}/rept/rept.cfg")
	


## Vérification de l'existence des répertoires de configuration
if [ ! -e "${rept}/conf/config-dpe.cfg" ]; then
	{
		tar -zxvf "/usr/share/osa-dpe/data.tar.gz" -C "${rept}/"
	}
fi

## Verification de la presence du paquet timeout
if type &>/dev/null timeout; then prst="oui"; fi
if [ "${prst}" != "oui" ]; then
	{
		tmo=""
		zenity --question --ok-label="Installer" --text="le paquet Timeout n est pas présent\\nVoulez-vous l installer maintenant ?" && tmo="oui"
		
		if [ "${tmo}" == "oui" ]; then
			{
				grep $(ls -i /var/lib/dpkg/lock | awk '{print $1}') /proc/locks >> /dev/null
				if [[ $? == 0 ]]; then
					{
						while true
						do
							zenity --question --text="Un autre gestionnaire de paquet est en cours.\nFermez le avant de cliquer sur OK." || break
							grep $(ls -i /var/lib/dpkg/lock | awk '{print $1}') /proc/locks >> /dev/null
							if [[ $? != 0 ]]; then
								{
									xterm -title 'label' -e "\
									echo -e \"\E[37;44m\033[1m $(echo "Entrez votre mot de passe administrateur") \033[0m\"
									eval $(echo 'sudo apt-get install timeout')"
									break
								}
							fi
						done
					}
				else
					{
						xterm -title 'label' -e "\
						echo -e \"\E[37;44m\033[1m $(echo "Entrez votre mot de passe administrateur") \033[0m\"
						eval $(echo 'sudo apt-get install timeout')"
					}
				fi
			}
		fi
	}
fi 

## On vérifie l'existance du paquet Geany
if [ -e /usr/bin/geany ]; then
	{
		gean="geany"
	}
else
	{
		#On récupère l'application par défaut pour le texte brut
		gean="$(xdg-mime query default text/plain | sed 's/\.desktop//g')"
	}
fi
						
if [ "${gean}" == "" ]; then
	{
		gean="xdg-open"
	}
fi

while true
do
	## Lecture de la configuration et inscription des variables
	eval $(grep -v "^#" "${rept}/conf/config-dpe.cfg")
	
	[[ -z "${nomdpe}" ]] && nomdpe="image"

	## On se positionne dans le dernier répertoire utilisé pour enregistrer les étiquettes
	cd "${chodpe}"

	## Boite GTKdialog de saisie des informations du DPE
	export MAIN_DIALOG='<window title="Créateur étiquettes energétiques" decorated="true" window_position="1" icon-name="gtk-home">
							<vbox>
								<hbox>
									<menubar>
										<menu>
											<menuitem stock="gtk-preferences">
												<action>'${gean}' '${rept}'/conf/config-dpe.cfg</action>
											</menuitem>
											<label>"Préférences"</label>
										</menu>
									</menubar>
								</hbox>
								<pixmap>
										<input file>"'${rept}'/conf/entete-dpe.png"</input>
								</pixmap>
								<frame          Valeur DPE                                                                                                                    Valeur GES>
									<hbox>
										<entry>
											<variable>val</variable>
										</entry>
										<text>
											<label>"kWh EP/m².an"</label>
										</text>

										<entry>
											<variable>val1</variable>
										</entry>
										<text>
											<label>"kgéqCO2/m².an"</label>
										</text>
									</hbox>
								</frame>
								<frame Choix des tailles>
									<hbox homogeneous="true">
										<checkbox>
											<variable>vig</variable>
											<label>'${tllv}' pixels</label>
										</checkbox>
										<checkbox>
											<variable>grand</variable>
											<label>'${tlg}' pixels</label>
										</checkbox>
										<checkbox>
											<variable>ntv</variable>
											<label>'${tlnat}' pixels</label>
											<default>true</default>
										</checkbox>
									</hbox>
								</frame>
								<hbox>
									<button>
										<label>"Choix dossier destination"</label>
										<input file stock="gtk-open"></input>
										<variable>FILE_BROWSE_DIRECTORY</variable>
										<action type="fileselect">chodpe</action>
									</button>
									<entry accept="directory">
										<variable>chodpe</variable>
										<default>'${chodpe}'</default>
									</entry>
										<text>
											<label>"Nom des fichiers"</label>
										</text>
										<entry>
											<variable>nomdpe</variable>
											<default>'${nomdpe}'</default>
										</entry>
								</hbox>
								<hbox homogeneous="true">
									<button ok></button>
									<button cancel></button>

								</hbox>
							</vbox>
							<action signal="delete-event">exit:cancel</action>
						</window>'

					VARIABLES=$(gtkdialog --program=MAIN_DIALOG)

					## inscription du résultat Gtkdialog dans un fichier temporaire
					echo ${VARIABLES} | sed 's/ /\n/g' > "${rept1}/var-dpe.txt"

					## Génération des variables
					eval ${VARIABLES}

					## Si annulation on quitte
					if [ "${EXIT}" != "OK" ]; then
						{
							exit 0
						}
					fi

					## Inscription des formats d'étiquettes à créer dans le fichier temporaire en fonction des choix dans la boite de dialoque
					[[ "${vig}" == "true" ]] && echo "tllv=\"${tllv}\"" >> "${rept1}/var-dpe.txt"
					[[ "${grand}" == "true" ]] && echo "tlg=\"${tlg}\"" >> "${rept1}/var-dpe.txt"
					[[ "${ntv}" == "true" ]] && echo "tlnat=\"${tlnat}\"" >> "${rept1}/var-dpe.txt"

					## Inscription du type d'images souhaitées dans le fichier temporaire en fonction des choix dans la boite de dialoque
					echo "tltyp=\"${tltyp}\"" >> "${rept1}/var-dpe.txt"

					## Remplacement du chemin par défaut inscrit dans le fichier de config par celui utilisé dans cette instance du script
					sed -i "s;chodpe=\".*\";chodpe=\"${chodpe}\";g" ${rept}/conf/config-dpe.cfg
								
					## Enregistrement du nom de ficher choisi
					grep "nomdpe=" ${rept}/conf/config-dpe.cfg >> /dev/null
					if [ $? == "0" ]; then
						{
							sed -i "s/nomdpe=\".*\"/nomdpe=\"${nomdpe}\"/g" ${rept}/conf/config-dpe.cfg
						}
					else
						{
							echo "nomdpe=\"${nomdpe}\"" >> ${rept}/conf/config-dpe.cfg
						}
					fi

					## On Lance la génération des étiquettes
					echo message: Etiquettes en création | zenity --notification --listen &
					/usr/share/osa-dpe/osa-dpe
					echo message: Etiquettes prêtes | zenity --notification --listen &
					
					timeout 20 zenity --question --text="Voules-vous créer d autres étiquettes ?" || break
done
timeout 20 zenity --question --text="Voulez-vous voir vos étiquettes ?" && xdg-open ${chodpe} &
exit 0
