#!/bin/bash
##

###################################################################################################################################################
## Copyright (C) 2010 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################

## On récupère les emplacements des répertoires de travail de OSagence
eval "$(grep 'rept1=\"' '/usr/share/osagence/osa-menu')"
eval $(grep 'rept=\"' "${rept1}/rept/rept.cfg")

## On vérifie l'existence des paramètres secrets (non fournis aux négociateurs)
if [ ! -e "${rept}/conf/osa-sec.cfg" ]; then
	{
		exit 0
	}
fi

## On supprime le précédant fichier de paramètres
rm -f "${rept1}/poliris/diff-prog.txt"

##
zenity --question --ok-label="Programmée" --text="Voulez-vous paramétrer la diffusion programmée?\nRépondez \"Non\" pour annuler toute programation et reprendre les diffusions manuelles" || exit 0
	
## Lecture de la configuration
eval $(grep -v "^#" "${rept}/conf/poliris.cfg")

## On crée le répertoire des fichiers Poliris si il n'existe pas
if [ ! -d "${rept1}/poliris" ]; then
	{
		mkdir "${rept1}/poliris"
	}
fi

## On choisi le mode de transfert des photos
confph=$(zenity --width=400 --height=200 --list --column "" --radiolist\
					--title="Choix du mode de transfert des photos" \
					--text="Si vous ne savez pas laissez le mode par défaut" \
					--column="" \
					TRUE "Ne renvoie que les photos modifièes" \
					FALSE "Renvoie de toutes les photos")
					
## On sélectionne les plates-formes disponibles
c="1"
plate=(${plateformes})
for pla in "${plate[@]}"; do
	eval "plat=\"\$${pla}_plat\""
	chpla[$c]="TRUE ${pla}#${plat}"
	((c++))
	
done

## On propose la sélection des plateformes à diffuser
sort_chpla=$( echo ${chpla[@]} | sed -e 's/ FALSE/\nFALSE/g' )

platefor=$(zenity --width=400 --height=400 --list --column "" --checklist\
					--title="Choix des plateformes de diffusion" \
					--text="Choisissez le ou la plateforme de diffusion" \
					--column="" \
					${sort_chpla[@]} )
					
## On écrit le fichier de paramètres de diffusion
echo -e "confph=\"${confph}\"\nplatefor=\"${platefor}\"" > "${rept1}/poliris/diff-prog.txt"
exit 0
