#!/bin/bash
##


###################################################################################################################################################
## Copyright (C) 2010 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################

## On récupère les emplacements des répertoires de travail de OSagence
eval "$(grep 'rept1=\"' '/usr/share/osagence/osa-menu')"
eval $(grep 'rept=\"' "${rept1}/rept/rept.cfg")

## On vérifie l'existence des paramètres secrets (non fournis aux négociateurs)
if [ ! -e "${rept}/conf/osa-sec.cfg" ]; then
	{
		exit 0
	}
fi

## Lecture de la configuration
eval $(grep -v "^#" "${rept}/conf/poliris.cfg")

while true
do
	export MAIN_DIALOG='<window title="Choix de la configuration à modifier." decorated="true" window_position="1" icon-name="gtk-home">
											<vbox>
												<hbox>
													<button><label>"Éditer liste noire"</label></button>
													<button><label>"Éditer liste blanche"</label></button>
													<button><label>"Modifier limites plateformes"</label></button>
													<button><label>"Quitter"</label></button>
												</hbox>
											</vbox>
											<action signal="delete-event">exit:Annuler</action>
										</window>'
										eval $(gtkdialog --program=MAIN_DIALOG)

	if [ "${EXIT}" == "Modifier limites plateformes" ]; then
		{
			## On choisi la plateforme dont on veut changer le nombre d'annonces maxi
			c="1"
			plate=(${plateformes})
			for pla in "${plate[@]}"; do
				eval "plat=\"\$${pla}_plat\""
				eval "maxp=\"\$${pla}_max\""
				chpla[$c]="FALSE ${pla}#${plat}#max=${maxp}"
				((c++))
				
			done
			sort_chpla=$( echo ${chpla[@]} | sed -e 's/ FALSE/\nFALSE/g' )

			platefor=$(zenity --width=400 --height=400 --list --column "" --radiolist\
								--title="Choix de la plateforme de diffusion" \
								--text="Choisissez la plateforme de diffusion dont vous voulez modifier les limites" \
								--column="" \
								${sort_chpla[@]} )
			if [ -z "${platefor}" ]; then
				{
					exit 0
				}
			fi

			maxd=$(echo "${platefor}" | cut -d"=" -f2)
			diffuseur=$(echo "${platefor}" | cut -d"#" -f2)
			diffcod=$(echo "${platefor}" | cut -d"#" -f1)

			maxch=$(zenity --entry --title="nb maxi d'annonces pour ${diffuseur}" --text="Validez un champ vide pour une diffusion illimitée" --entry-text="${maxd}")
			[[ "${maxch}" =~ ^[[:digit:]]+$ ]] || maxch=""
			sed -i "s/${diffcod}_max=\"${maxd}\"/${diffcod}_max=\"${maxch}\"/g" "${rept}/conf/poliris.cfg"
			exit 0
		}
	fi

	if [ "${EXIT}" == "Éditer liste blanche" ]; then
		{
			## On s'assure de l'existence de la Whitelist et on trie son contenu
					touch "${rept}/conf/whitelist.lst"
					sed -i "/^$/d" "${rept}/conf/whitelist.lst"
					lgn=$(wc -l "${rept}/conf/whitelist.lst" | cut -d" " -f1)
					if [ "${lgn}" -gt "0" ]; then
						{
							touch "${rept}/conf/whitelist1.lst" 
						}
					else
						{
							echo "00000" > "${rept}/conf/whitelist1.lst"
						}
					fi
					sort "${rept}/conf/whitelist.lst" | grep [[:digit:]] | grep -v [[:alpha:]] | uniq >> "${rept}/conf/whitelist1.lst"

			whitelist=$(zenity --text-info --filename="${rept}/conf/whitelist1.lst" --title="Liste blanche" --text="Inscrivez ici les n° de mandat qui doivent être plubliés quoi qu'il arrive" --width="300" --height="400" --editable 2)
			if [ $? == "0" ]; then
				{
					echo "${whitelist}" > "${rept}/conf/whitelist.lst"
				}
			fi

			grep -v "00000" "${rept}/conf/whitelist.lst" | sort | uniq > "${rept}/conf/whitelist1.lst"
			rm "${rept}/conf/whitelist.lst"
			mv "${rept}/conf/whitelist1.lst" "${rept}/conf/whitelist.lst"
		}
	fi

	if [ "${EXIT}" == "Éditer liste noire" ]; then
		{
			## On s'assure de l'existence de la blacklist et on trie son contenu
					touch "${rept}/conf/blacklist.lst"
					sed -i "/^$/d" "${rept}/conf/blacklist.lst"
					lgn=$(wc -l "${rept}/conf/blacklist.lst" | cut -d" " -f1)
					if [ "${lgn}" -gt "0" ]; then
						{
							touch "${rept}/conf/blacklist1.lst" 
						}
					else
						{
							echo "00000" > "${rept}/conf/blacklist1.lst"
						}
					fi
					sort "${rept}/conf/blacklist.lst" | grep [[:digit:]] | grep -v [[:alpha:]] | uniq >> "${rept}/conf/blacklist1.lst"
					
			blacklist=$(zenity --text-info --filename="${rept}/conf/blacklist1.lst" --title="Liste Noire" --text="Inscrivez ici les n° de mandats qui seront supprimé en priorité si le seuil de diffusion de la plateforme est dépassé" --width="300" --height="400" --editable 2)
			if [ $? == "0" ]; then
				{
					echo "${blacklist}" > "${rept}/conf/blacklist.lst"
				}
			fi

			grep -v "00000" "${rept}/conf/blacklist.lst" | sort | uniq > "${rept}/conf/blacklist1.lst"
			rm "${rept}/conf/blacklist.lst"
			mv "${rept}/conf/blacklist1.lst" "${rept}/conf/blacklist.lst"
		}
	fi
	
	if [ "${EXIT}" == "Quitter" ]; then
		{
			break
		}
	fi
done

exit 0
								
