#!/bin/bash
##


###################################################################################################################################################
## Copyright (C) 2010 www.2aide.fr                                                                                                               ##
##                                                                                                                                               ##
## Ce programme est un logiciel libre, vous pouvez le redistribuer et / ou le modifier selon les termes de la Licence Publique Générale GNU      ##
## telle que publiée par la Free Software Foundation; soit la version 2 de la Licence, ou (à votre choix) toute version ultérieure.              ##
##                                                                                                                                               ##
## Ce programme est distribué dans l'espoir qu'il sera utile, mais SANS AUCUNE GARANTIE, sans même la garantie implicite de COMMERCIALISATION    ##
## ou D'ADAPTATION A UN USAGE PARTICULIER. Voir la Licence Publique Générale GNU, disponible ici http://www.opensource.org/licenses/gpl-2.0.php  ##
## pour plus de détails.                                                                                                                         ##
##                                                                                                                                               ##
## Vous devriez avoir reçu une copie de la Licence Publique Générale GNU avec ce programme, sinon, écrivez à                                     ##
## Free Software Foundation, Inc, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA                                                          ##
##                                                                                                                                               ##
##                                                                                                                                               ##
##                                 En 2 mots, vous étes libre d'utiliser, de copier et de distribuer ce programme                                ##
##                                  à condition de soumettre votre copie à la même licence GPL v-2 ou ultérieure                                 ##
##                                                                                                                                               ##
###################################################################################################################################################

## On récupère les emplacements des répertoires de travail de OSagence
if [ -e "/usr/share/osagence/osa-menu" ]; then
	{
		eval "$(grep 'rept1=\"' '/usr/share/osagence/osa-menu')"
	}
else
	{
		rept1="$HOME/.osa-tmp"
		if [ ! -d "${rept1}/rept" ]; then
			{
				mkdir -p "${rept1}"
			}
		fi
	}
fi

/usr/share/osa-villes/osa-villes
	
	rm -f "${rept1}/ville.tmp"
	rm -f "${rept1}/villemand1.tmp"
	rm -f "${rept1}/villemand.tmp"
	rm -f "${rept1}/secteur.tmp"
	rm -f /tmp/listvil.tmp
	exit 0


